// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "github.com/fathersson/wb-demo-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// CacheInterface is an autogenerated mock type for the CacheInterface type
type CacheInterface struct {
	mock.Mock
}

type CacheInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheInterface) EXPECT() *CacheInterface_Expecter {
	return &CacheInterface_Expecter{mock: &_m.Mock}
}

// GetCache provides a mock function with given fields: orderUID
func (_m *CacheInterface) GetCache(orderUID string) (models.Order, bool) {
	ret := _m.Called(orderUID)

	if len(ret) == 0 {
		panic("no return value specified for GetCache")
	}

	var r0 models.Order
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (models.Order, bool)); ok {
		return rf(orderUID)
	}
	if rf, ok := ret.Get(0).(func(string) models.Order); ok {
		r0 = rf(orderUID)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(orderUID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// CacheInterface_GetCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCache'
type CacheInterface_GetCache_Call struct {
	*mock.Call
}

// GetCache is a helper method to define mock.On call
//   - orderUID string
func (_e *CacheInterface_Expecter) GetCache(orderUID interface{}) *CacheInterface_GetCache_Call {
	return &CacheInterface_GetCache_Call{Call: _e.mock.On("GetCache", orderUID)}
}

func (_c *CacheInterface_GetCache_Call) Run(run func(orderUID string)) *CacheInterface_GetCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *CacheInterface_GetCache_Call) Return(_a0 models.Order, _a1 bool) *CacheInterface_GetCache_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CacheInterface_GetCache_Call) RunAndReturn(run func(string) (models.Order, bool)) *CacheInterface_GetCache_Call {
	_c.Call.Return(run)
	return _c
}

// SetCache provides a mock function with given fields: orderUID, order
func (_m *CacheInterface) SetCache(orderUID string, order models.Order) {
	_m.Called(orderUID, order)
}

// CacheInterface_SetCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCache'
type CacheInterface_SetCache_Call struct {
	*mock.Call
}

// SetCache is a helper method to define mock.On call
//   - orderUID string
//   - order models.Order
func (_e *CacheInterface_Expecter) SetCache(orderUID interface{}, order interface{}) *CacheInterface_SetCache_Call {
	return &CacheInterface_SetCache_Call{Call: _e.mock.On("SetCache", orderUID, order)}
}

func (_c *CacheInterface_SetCache_Call) Run(run func(orderUID string, order models.Order)) *CacheInterface_SetCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(models.Order))
	})
	return _c
}

func (_c *CacheInterface_SetCache_Call) Return() *CacheInterface_SetCache_Call {
	_c.Call.Return()
	return _c
}

func (_c *CacheInterface_SetCache_Call) RunAndReturn(run func(string, models.Order)) *CacheInterface_SetCache_Call {
	_c.Run(run)
	return _c
}

// NewCacheInterface creates a new instance of CacheInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheInterface {
	mock := &CacheInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
