// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka_go "github.com/segmentio/kafka-go"

	mock "github.com/stretchr/testify/mock"
)

// MessageReader is an autogenerated mock type for the MessageReader type
type MessageReader struct {
	mock.Mock
}

type MessageReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageReader) EXPECT() *MessageReader_Expecter {
	return &MessageReader_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MessageReader) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MessageReader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MessageReader_Expecter) Close() *MessageReader_Close_Call {
	return &MessageReader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MessageReader_Close_Call) Run(run func()) *MessageReader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MessageReader_Close_Call) Return(_a0 error) *MessageReader_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageReader_Close_Call) RunAndReturn(run func() error) *MessageReader_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CommitMessages provides a mock function with given fields: ctx, msgs
func (_m *MessageReader) CommitMessages(ctx context.Context, msgs ...kafka_go.Message) error {
	_va := make([]interface{}, len(msgs))
	for _i := range msgs {
		_va[_i] = msgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CommitMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...kafka_go.Message) error); ok {
		r0 = rf(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageReader_CommitMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitMessages'
type MessageReader_CommitMessages_Call struct {
	*mock.Call
}

// CommitMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs ...kafka_go.Message
func (_e *MessageReader_Expecter) CommitMessages(ctx interface{}, msgs ...interface{}) *MessageReader_CommitMessages_Call {
	return &MessageReader_CommitMessages_Call{Call: _e.mock.On("CommitMessages",
		append([]interface{}{ctx}, msgs...)...)}
}

func (_c *MessageReader_CommitMessages_Call) Run(run func(ctx context.Context, msgs ...kafka_go.Message)) *MessageReader_CommitMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]kafka_go.Message, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(kafka_go.Message)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MessageReader_CommitMessages_Call) Return(_a0 error) *MessageReader_CommitMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageReader_CommitMessages_Call) RunAndReturn(run func(context.Context, ...kafka_go.Message) error) *MessageReader_CommitMessages_Call {
	_c.Call.Return(run)
	return _c
}

// FetchMessage provides a mock function with given fields: ctx
func (_m *MessageReader) FetchMessage(ctx context.Context) (kafka_go.Message, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchMessage")
	}

	var r0 kafka_go.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (kafka_go.Message, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) kafka_go.Message); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(kafka_go.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageReader_FetchMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMessage'
type MessageReader_FetchMessage_Call struct {
	*mock.Call
}

// FetchMessage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MessageReader_Expecter) FetchMessage(ctx interface{}) *MessageReader_FetchMessage_Call {
	return &MessageReader_FetchMessage_Call{Call: _e.mock.On("FetchMessage", ctx)}
}

func (_c *MessageReader_FetchMessage_Call) Run(run func(ctx context.Context)) *MessageReader_FetchMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MessageReader_FetchMessage_Call) Return(_a0 kafka_go.Message, _a1 error) *MessageReader_FetchMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageReader_FetchMessage_Call) RunAndReturn(run func(context.Context) (kafka_go.Message, error)) *MessageReader_FetchMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageReader creates a new instance of MessageReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageReader {
	mock := &MessageReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
