// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/segmentio/kafka-go"

	mock "github.com/stretchr/testify/mock"
)

// MessageWriter is an autogenerated mock type for the MessageWriter type
type MessageWriter struct {
	mock.Mock
}

type MessageWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageWriter) EXPECT() *MessageWriter_Expecter {
	return &MessageWriter_Expecter{mock: &_m.Mock}
}

// WriteMessages provides a mock function with given fields: ctx, msgs
func (_m *MessageWriter) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	_va := make([]interface{}, len(msgs))
	for _i := range msgs {
		_va[_i] = msgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WriteMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...kafka.Message) error); ok {
		r0 = rf(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MessageWriter_WriteMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteMessages'
type MessageWriter_WriteMessages_Call struct {
	*mock.Call
}

// WriteMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs ...kafka.Message
func (_e *MessageWriter_Expecter) WriteMessages(ctx interface{}, msgs ...interface{}) *MessageWriter_WriteMessages_Call {
	return &MessageWriter_WriteMessages_Call{Call: _e.mock.On("WriteMessages",
		append([]interface{}{ctx}, msgs...)...)}
}

func (_c *MessageWriter_WriteMessages_Call) Run(run func(ctx context.Context, msgs ...kafka.Message)) *MessageWriter_WriteMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]kafka.Message, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(kafka.Message)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MessageWriter_WriteMessages_Call) Return(_a0 error) *MessageWriter_WriteMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MessageWriter_WriteMessages_Call) RunAndReturn(run func(context.Context, ...kafka.Message) error) *MessageWriter_WriteMessages_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageWriter creates a new instance of MessageWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageWriter {
	mock := &MessageWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
