// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/fathersson/wb-demo-service/internal/models"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// GetOrderById provides a mock function with given fields: ctx, orderUID
func (_m *OrderRepository) GetOrderById(ctx context.Context, orderUID string) (models.Order, error) {
	ret := _m.Called(ctx, orderUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderById")
	}

	var r0 models.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Order, error)); ok {
		return rf(ctx, orderUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Order); ok {
		r0 = rf(ctx, orderUID)
	} else {
		r0 = ret.Get(0).(models.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrderById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderById'
type OrderRepository_GetOrderById_Call struct {
	*mock.Call
}

// GetOrderById is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUID string
func (_e *OrderRepository_Expecter) GetOrderById(ctx interface{}, orderUID interface{}) *OrderRepository_GetOrderById_Call {
	return &OrderRepository_GetOrderById_Call{Call: _e.mock.On("GetOrderById", ctx, orderUID)}
}

func (_c *OrderRepository_GetOrderById_Call) Run(run func(ctx context.Context, orderUID string)) *OrderRepository_GetOrderById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *OrderRepository_GetOrderById_Call) Return(_a0 models.Order, _a1 error) *OrderRepository_GetOrderById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrderById_Call) RunAndReturn(run func(context.Context, string) (models.Order, error)) *OrderRepository_GetOrderById_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: query, args
func (_m *OrderRepository) Query(query string, args ...interface{}) (*sql.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *sql.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) (*sql.Rows, error)); ok {
		return rf(query, args...)
	}
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *sql.Rows); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type OrderRepository_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - query string
//   - args ...interface{}
func (_e *OrderRepository_Expecter) Query(query interface{}, args ...interface{}) *OrderRepository_Query_Call {
	return &OrderRepository_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{query}, args...)...)}
}

func (_c *OrderRepository_Query_Call) Run(run func(query string, args ...interface{})) *OrderRepository_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *OrderRepository_Query_Call) Return(_a0 *sql.Rows, _a1 error) *OrderRepository_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_Query_Call) RunAndReturn(run func(string, ...interface{}) (*sql.Rows, error)) *OrderRepository_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function with given fields: query, args
func (_m *OrderRepository) QueryRow(query string, args ...interface{}) *sql.Row {
	var _ca []interface{}
	_ca = append(_ca, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 *sql.Row
	if rf, ok := ret.Get(0).(func(string, ...interface{}) *sql.Row); ok {
		r0 = rf(query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}

	return r0
}

// OrderRepository_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type OrderRepository_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - query string
//   - args ...interface{}
func (_e *OrderRepository_Expecter) QueryRow(query interface{}, args ...interface{}) *OrderRepository_QueryRow_Call {
	return &OrderRepository_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{query}, args...)...)}
}

func (_c *OrderRepository_QueryRow_Call) Run(run func(query string, args ...interface{})) *OrderRepository_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *OrderRepository_QueryRow_Call) Return(_a0 *sql.Row) *OrderRepository_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_QueryRow_Call) RunAndReturn(run func(string, ...interface{}) *sql.Row) *OrderRepository_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepository) SaveOrder(ctx context.Context, order models.Order) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Order) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepository_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type OrderRepository_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order models.Order
func (_e *OrderRepository_Expecter) SaveOrder(ctx interface{}, order interface{}) *OrderRepository_SaveOrder_Call {
	return &OrderRepository_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order)}
}

func (_c *OrderRepository_SaveOrder_Call) Run(run func(ctx context.Context, order models.Order)) *OrderRepository_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Order))
	})
	return _c
}

func (_c *OrderRepository_SaveOrder_Call) Return(_a0 error) *OrderRepository_SaveOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepository_SaveOrder_Call) RunAndReturn(run func(context.Context, models.Order) error) *OrderRepository_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
